# The URL the site will be built for
base_url = "https://better-web-alliance.net/"

# The site title and description; used in feeds by default.
title = "Better Web Alliance"
description = ""

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The taxonomies to be rendered for that site and their configuration
taxonomies = [
    { name = "resources", paginate_by = 10 }, # 5 items per page for a term
]

[extra.taxonomies.description.resources]
resources = "Books, guides and tools to help you make the web a better place."
accessibility = "Articles and tools related to a11y (accessibility)."
articles = "In-depth tutorials and other long-form articles."
performance = "Articles and tools relating to web performance."
privacy = "Articles and tools related to online privacy."
sustainability = "Articles and tools related to sustainability."
tools = "Tools and utilities to assist in improving websites."
